Add small self-contained example of issue
In "src/index.ts" we import the "./hello" dir, which should work because
the file "./hello/index.ts" exists.

Works in vscode and tsc, but "rollup -c" fails with the following message:

  Error: Could not resolve './hello' from src/index.ts
      at error (/home/mike/.npm/lib/node_modules/rollup/dist/rollup.js:3460:30)
      at /home/mike/.npm/lib/node_modules/rollup/dist/rollup.js:21850:25